Create short welcome description of Libra and these products
Libra-foundation/.github pull request #1
Opened 2022-12-29 18:51 UTC by Beladric

Like for Correlatio company, a description is now available for GitHub organization of Libra foundation. This description will be shown on the main page of the organization. It's hold a description of what's Libra, products offer, etc.

PS : Logo's doesn't work as long as development branch isn't merged into main. If something is missing, don't hesitate to describe it in a short comment.

2023-01-01 09:21 UTC, galyfray requested changes
Hi ! Sorry for the time taken to review this PR, I was pretty busy lately. As always you made an excellent work, but as expected by you this is way too much corporate for me. Being corporate with Correlatio is normal as the goal of this organization is to generate profit, however this is not the case here. As we do not sell anything, as we are talking to different persons, we need to adapt the speech to the audience.

2023-01-01 09:21 UTC, galyfray commented on profile/README.md
> +    Libra is a branch of E-constellatio company. Libra offers abundant free numerical solutions like softwares, websites, servers, templates, etc.
Not sure if `informatic` is the right word, but one thing is sure : `numerical` wasn't ^^. Numerical, belongs to realm of numbers and does not have much to do with computer science, software etc ... 
```suggestion
    Libra is a branch of E-constellatio company. Libra offers abundant free and open source informatic solutions like softwares, websites, servers, templates, etc.
```

2023-01-01 09:21 UTC, galyfray commented on profile/README.md
> +        Highlighting products
We sell products, but the goal here is not to sell them. Maybe something like "projects" would better fit in this context.

2023-01-01 09:21 UTC, galyfray commented on profile/README.md
> +<p>Because we believe in collaboration and its benefits at E-constellatio we created Collaboratio. A pull-together website applied to documentation, diagrams, project management, etc. Take all advant
No need to be this much corporate, we created it because no current free solution could fulfill our requirements. When I'm checking for open source projects to contributes to, I tend to avoid corporate projects. As we want peoples to help on our projects, putting the emphasis on the open source feel, the free to contribute, free to use, warm and helpful community would be better in my opinion.

2023-01-01 09:21 UTC, galyfray commented on profile/README.md
> +<p>React template is a free and advanced template for react projects. Based on `react-scripts`, react template developed by E-constellatio includes more features like advanced ESLint rules, environme
The feeling I have with our template is that we want this project to help us create more reliable, easier to maintain, more newcomer friendly code. This pass thought hardened rules, to keep the code consistent and help everyone avoid known mistakes, and a set of utility packages that automates most of the annoying work. The features are advenced-ish to set up, but not to use. This distinction is important to attract people that are not really familiar with TS. And also we might want to say this is a TS template :)

2023-01-02 16:00 UTC, galyfray requested changes
The exercise is far from simple, and I have to say that I appreciate this revision way more than the previous one.

2023-01-02 16:23 UTC, Beladric commented on profile/README.md
> +<p>Collaboratio is a pull-together website applied to documentations, diagrams, projects management, etc. Collaboratio was created because no free solution fulfill our requirements. Moreover, we thin
I think `and we hope you feel free to contribute` is better. The `to it` is repetitive and sound weird.

2023-01-02 16:55 UTC, galyfray commented on profile/README.md
> +<p>Collaboratio is a pull-together website applied to documentations, diagrams, projects management, etc. Collaboratio was created because no free solution fulfill our requirements. Moreover, we thin
I think that a simple `feel free to contribute` would be better. Because the expression  `feel free to <verbe>` is an invitation to do something, adding a `we hope` before an invitation is in my opinion strange.

2023-01-02 17:25 UTC, galyfray requested changes

2023-01-02 17:25 UTC, galyfray commented on profile/README.md
> +<p>React template is a free, reliable and easy to maintain template for react project. Based on `react-scripts`, we have added hardened rules, to keep the code consistent and help everyone avoids mis
```suggestion
<p>React template is a free, reliable and easy to maintain template for react project. Based on `react-scripts`, we configured a set of utility packages that automates most of the annoying work. To help everyone avoid common mistakes and keep the code nice and tidy, we added hardened rules.  This template is particularly useful for newcomers to guide them through the learning of React Typescript with good practices.</p>
```

2023-01-02 17:25 UTC, galyfray commented on profile/README.md
> +<p>It's always difficult to code properly when you start codding with a permissive language. In the same mind as React template, we created Python template, a free and open template for all python pr
> In the same mind as React template,

That's not English, that literal translation of an idiomatic expression.  
>this template fix limits.

What limits ? 

> Django template is very helpful because it's contained standardized logs, connection to OAuth2 server, etc.

Firstly this template will hold a branch dedicated to Django, it currently does not and is quite far from this ...
Secondly, this kinda sounds like google translated things cobbled together that you could find in a scam. 
I mean : "it's contained" ...

2023-01-02 17:25 UTC, galyfray commented on profile/resources/PythonTemplate.svg
> +<stop offset="1" stop-color="#61DAFB" stop-opacity="0"/>
Why did you add an alpha to this gradient ?

2023-01-02 19:00 UTC, galyfray requested changes
Excellent work ! I have one question about a part that do not understand very well ...

2023-01-02 19:00 UTC, galyfray commented on profile/README.md
> +<p>It's always difficult to code properly when you start codding with a permissive language. In the same vein as React template, we created Python template, a free and open template for all python pr
> react-scripts test

I am not sure, I do not exactly understand what you mean here. Could you explain to me ? 

```suggestion
<p>It's always difficult to code properly when you start codding with a permissive language. In the same vein as React template, we created Python template, a free and open template for all python projects. Like its namesake, python template embedded advanced linting rules, automates boring work and so on. Very advantageous, this template set boundaries to working team. <br> Moreover, Python template hold branches for specific Python projects, such as a Django branch. A helpful Django template with standardized logs, connection to OAuth2 server, etc.  </p>
```

2023-01-02 19:35 UTC, galyfray approved these changes
Seems good to me.

2023-01-02 19:36 UTC, merged