Pull request template
Libra-foundation/.github pull request #2
Opened 2023-01-02 13:18 UTC by Beladric

New pull request templates for React template and Python template are available. They look like each other, with only one difference. 

I would like to know If I create one template per project and more changes between them will arrive later, or if I create only one global template for all projects ?

2023-01-02 14:55 UTC, galyfray commented
I think you misunderstood the meaning of "default templates". Default templates are generic, they are shared by all the repository that will be created in the Libra foundation. If a repository need more specific templates, we can override them by creating a template in the said repository. This mean that creating here a template for the React repo and another for the python repo does not make sens.

2023-01-02 14:58 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PYTHON_TEMPLATE_PULL_REQUEST_TEMPLATE.md
> +## Type of change
The type of change could be signaled through labels or a tag at the beginning of the PR's title. Either of these ways would enable us to see the type of change before reading the PR.

2023-01-02 16:38 UTC, galyfray requested changes
The template should be more gentle with the reader, more "please" and other kind words, this template aims to gently guide the contributors toward a good PR. From my personal experience, the templates themselves are the skeleton of the PR, and the TODO-ish list that you wrote at the beginning would be in a "requirements" section. This way, we could monitor the fact that the contributor checked the boxes and thus should be aware that he should have completed the requirements.
Again from my experience I quickly flew away from projects where the template was aggressive mostly because when the template is aggressive the reviewers also are.

2023-01-02 16:38 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +***This part help you to don't forget anything before create pull request, If everything seem good you could delete it***
```suggestion
***This part help you to don't forget anything before create pull request, If everything seem good you can delete it***
```

2023-01-02 16:38 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +Thanks for contribution :heart:. Before creating pull
```suggestion
Thanks for your contribution :heart:. Before creating pull
```

2023-01-02 16:38 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +request you were able to check :
```suggestion
requestplease make sure that:
```

2023-01-02 16:38 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +- [ ] You have performed a self-review of my code
```suggestion
- [ ] You have performed a self-review of your code
```

2023-01-02 16:38 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +- [ ] You have commented my code, particularly in hard-to-understand areas
```suggestion
- [ ] You have commented your code, particularly in hard-to-understand areas
```

2023-01-02 16:38 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +- [ ] You have added tests that prove my fix is effective or that my feature works
```suggestion
- [ ] You have added tests that prove your fix is effective or that your feature works
```

2023-01-02 16:38 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +Your pull request title must contain type of change plus a short description. You have the choice between :
Title tags are more often in the for `[TAG]` where the tag is minimal. I do not think that's a great idea to restrict to a list. Adding some examples is a good way of ensuring common tags are respected in a gentle way.

2023-01-02 16:38 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +## How Has This Been Tested?
This section does not feel useful, we rely on unit tests and/or integration tests. The answer should always be "I created the relevant test cases".

2023-01-02 19:10 UTC, galyfray requested changes
I think that the skeleton of the PR is kind of empty, we should have a more in depth discussion of what we would like a PR to looks like.

2023-01-02 19:10 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +Thanks for your contribution :heart:. Before creating pull
```suggestion
Thanks for your contribution :heart:. Before creating a pull
```

2023-01-02 19:10 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +Your pull request title must contain type of change plus a short description. Title type must be relevant and minimal (one or two words), this is a non-exhaustive list:
The tag must be relevant and minimal, the title can be longer than two words.

2023-01-02 19:10 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
>  - Breaking change (fix or feature that would cause existing functionality to not work as expected)
I am more a fan of this type of tags :

```suggestion
- [BUG]: bug fix
- [FEATURE]: changes which adds functionality
- [BREAKING]: prepend this tag to any PR that breaks retro-compatibility.
```
I prefer them as they are shorter and clearly distinct from the title.
What do you prefer ?

2023-01-02 19:14 UTC, galyfray commented
We might also want peoples to add relevant closing tags to the PR that fixes bugs, see this [documentation](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) if you want more details on what I mean.

2023-01-03 07:44 UTC, galyfray requested changes
All I can see here is great, as said earlier I would like to discuss with you about the skeleton of the PR. Apart from this ongoing conversation, this PR is good to go !

2023-01-03 13:58 UTC, galyfray requested changes

2023-01-03 13:58 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +of [checks part](#Checks), includes all following parts and title respect rule.
```suggestion
of the [checks part](#Checks), including all following parts and the title rules as this makes our lives easier :heart:.
```

2023-01-03 13:58 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +Your pull request title must contain a tag type plus a short description. Tag must be relevant and minimal, this is a
```suggestion
Your pull request title must contain a tag type plus a short description. Tags must be relevant and minimal, here is a
```

2023-01-03 13:58 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +- [ ] Any dependent changes have been merged and published in downstream modules
I do not think this one is really needed. I mean, the down streamed modules should update in response to the approved changes of the repo, not the opposite, right ?

2023-01-03 14:32 UTC, galyfray requested changes

2023-01-03 14:32 UTC, galyfray commented on PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
> +Disclaimer :exclamation: Issues are formatted using markdown, a useful summary of the features provided by GitHub can be found here.
Missing link.

2023-01-03 14:41 UTC, galyfray requested changes
could add a part about reading the code of conduct and the contributing.md ?

2023-01-03 14:45 UTC, Beladric commented
> could add a part about reading the code of conduct and the contributing.md ?

It's already done in checks part ^^

2023-01-03 14:47 UTC, galyfray commented
> > could add a part about reading the code of conduct and the contributing.md ?
> 
> It's already done in checks part ^^

It seems like it is not ^^
> ```md

- [ ] Your code follows the style guidelines of this project
- [ ] You have performed a self-review of your code
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have made corresponding changes to the documentation
- [ ] Your changes generate no new warnings
- [ ] You have added tests that prove your fix is effective or that your feature works
- [ ] New and existing unit tests pass locally with your changes
```

2023-01-03 18:11 UTC, galyfray approved these changes
All good.

2023-01-03 18:12 UTC, merged